# For a quick mongo/elasticSearch local environment

version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/data:/data/db
  opensearch:
    container_name: hcmi-opensearch
    image: 'opensearchproject/opensearch:latest'
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./docker/opensearch/data:/usr/share/opensearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=workflow.opensearch
      - cluster.routing.allocation.disk.threshold_enabled=false
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx2048m
      - DISABLE_SECURITY_PLUGIN=true
