name: hcmi
services:
  hcmi-ui:
    build:
      context: .
      target: hcmi-ui
    container_name: hcmi-ui
    depends_on:
      - hcmi-cms
      - hcmi-api
    image: hcmi-ui
    ports:
      - 3000:3000
  hcmi-api:
    build:
      context: .
      target: hcmi-api
    container_name: hcmi-api
    depends_on:
      - mongo
      - opensearch
    image: hcmi-api
    ports:
      - 5050:5050
  hcmi-cms:
    build:
      context: .
      target: hcmi-cms
    container_name: hcmi-cms
    depends_on:
      - mongo
      - opensearch
    image: hcmi-cms
    ports:
      - 8080:8080
  mongo:
    container_name: hcmi-mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/data:/data/db
  opensearch:
    container_name: hcmi-opensearch
    image: 'opensearchproject/opensearch:latest'
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./docker/opensearch/data:/usr/share/opensearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=workflow.opensearch
      - cluster.routing.allocation.disk.threshold_enabled=false
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx2048m
      - DISABLE_SECURITY_PLUGIN=true
