module.exports = {
  /**
   * Application configuration section
   * http://pm2.keymetrics.io/docs/usage/application-declaration/
   */
  apps: [
    {
      name: 'hcmi-cms',
      script: 'index.js',
      env: {
        PORT: 8080,
        ES_UPDATE_INDEX: 'hcmi-update',
      },
      env_dev: {
        AUTH_ENABLED: false,
        ES_INDEX: 'hcmi',
        ES_HOST: 'http://host.docker.internal',
        ES_PASS: 'password',
        ES_PORT: 9200,
        ES_URL: 'http://host.docker.internal:9200',
        ES_USER: 'elastic',
        IAM_USER_KEY: 'ADD-KEY',
        IAM_USER_SECRET: 'ADD-SECRET',
        LOG_LEVEL: 'debug',
        NODE_ENV: 'dev',
        MONGO_COLLECTION: 'models',
        MONGO_DB_NAME: 'hcmi',
        MONGODB_URI: 'mongodb://host.docker.internal:27017/hcmi',
        MONGO_URL: 'mongodb://host.docker.internal:27017',
        MONGO_USER_COLLECTION: 'users',
        REDIRECT_URIS: ['http://localhost:5050/'],
        S3_BUCKET: 'hcmi-demo',
        SEARCH_ENGINE: 'opensearch',
        SEARCH_ENGINE_AUTH_TYPE: undefined,
        SEARCH_ENGINE_AUTH_REGION: undefined,
        SEARCH_ENGINE_AUTH_SERVICE: undefined,
      },
      env_staging: {
        AUTH_ENABLED: process.env.AUTH_ENABLED,
        ES_INDEX: process.env.ES_INDEX,
        ES_HOST: process.env.ES_HOST,
        ES_PASS: process.env.ES_PASS,
        ES_PORT: process.env.ES_PORT,
        ES_URL: process.env.ES_URL,
        ES_USER: process.env.ES_USER,
        IAM_USER_KEY: process.env.IAM_USER_KEY,
        IAM_USER_SECRET: process.env.IAM_USER_SECRET,
        LOG_LEVEL: 'info',
        NODE_ENV: 'staging',
        MONGO_COLLECTION: process.env.MONGO_COLLECTION,
        MONGO_DB_NAME: process.env.MONGO_DB_NAME,
        MONGODB_URI: process.env.MONGODB_URI,
        MONGO_URL: process.env.MONGODB_URL,
        MONGO_USER_COLLECTION: process.env.MONGO_USER_COLLECTION,
        REDIRECT_URIS: process.env.REDIRECT_URIS,
        S3_BUCKET: process.env.S3_BUCKET,
        SEARCH_ENGINE: process.env.SEARCH_ENGINE,
        SEARCH_ENGINE_AUTH_TYPE: process.env.SEARCH_ENGINE_AUTH_TYPE,
        SEARCH_ENGINE_AUTH_REGION: process.env.SEARCH_ENGINE_AUTH_REGION,
        SEARCH_ENGINE_AUTH_SERVICE: process.env.SEARCH_ENGINE_AUTH_SERVICE,
      },
      env_prd: {
        AUTH_ENABLED: process.env.AUTH_ENABLED,
        ES_INDEX: process.env.ES_INDEX,
        ES_HOST: process.env.ES_HOST,
        ES_PASS: process.env.ES_PASS,
        ES_PORT: process.env.ES_PORT,
        ES_URL: process.env.ES_URL,
        ES_USER: process.env.ES_USER,
        IAM_USER_KEY: process.env.IAM_USER_KEY,
        IAM_USER_SECRET: process.env.IAM_USER_SECRET,
        LOG_LEVEL: 'info',
        NODE_ENV: 'staging',
        MONGO_COLLECTION: process.env.MONGO_COLLECTION,
        MONGO_DB_NAME: process.env.MONGO_DB_NAME,
        MONGODB_URI: process.env.MONGODB_URI,
        MONGO_URL: process.env.MONGODB_URL,
        MONGO_USER_COLLECTION: process.env.MONGO_USER_COLLECTION,
        REDIRECT_URIS: process.env.REDIRECT_URIS,
        S3_BUCKET: process.env.S3_BUCKET,
        SEARCH_ENGINE: process.env.SEARCH_ENGINE,
        SEARCH_ENGINE_AUTH_TYPE: process.env.SEARCH_ENGINE_AUTH_TYPE,
        SEARCH_ENGINE_AUTH_REGION: process.env.SEARCH_ENGINE_AUTH_REGION,
        SEARCH_ENGINE_AUTH_SERVICE: process.env.SEARCH_ENGINE_AUTH_SERVICE,
      },
    },
  ],
};
