export const modelStatus = {
  unpublished: 'unpublished',
  published: 'published',
  unpublishedChnages: 'unpublished changes',
  other: 'other',
};

export const primarySites = [
  'abdomen',
  'abdomen/pelvis',
  'abdominal wall',
  'acetabulum',
  'adenoid',
  'adipose',
  'adrenal',
  'alveolar ridge',
  'amniotic fluid',
  'ampulla of vater',
  'anal canal',
  'anal sphincter',
  'ankle',
  'anorectum',
  'antecubital fossa',
  'anterior mediastinum',
  'antrum/distal',
  'anus',
  'aorta',
  'aortic body',
  'appendix',
  'aqueous fluid',
  'arm,',
  'artery',
  'ascending colon',
  'ascending colon hepatic flexure',
  'ascites/peritoneum',
  'auditory canal',
  'autonomic nervous system',
  'axilla',
  'axillary',
  'axillary lymph nodes',
  'axillary/brachial',
  'back',
  'base of tongue',
  'bile duct',
  'bladder',
  'blood',
  'blood vessel',
  'body of pancreas',
  'bone',
  'bone marrow',
  'bowel',
  'brain',
  'brain stem',
  'breast',
  'broad ligament',
  'bronchial',
  'bronchiole',
  'bronchus',
  'bronchus and lung',
  'brow',
  'buccal cavity',
  'buccal mucosa',
  'buttock',
  'calcaneus',
  'calf',
  'capillary',
  'cardia/proximal',
  'carina',
  'carotid artery',
  'carotid body',
  'carpus',
  'cartilage',
  'cecum',
  'celiac axis/retrocrural',
  'celiac axis/retrocrural/upper para-aortic',
  'central line catheter',
  'central nervous system',
  'cerebellum',
  'cerebral cortex',
  'cerebrospinal fluid',
  'cerebrum',
  'cervical',
  'cervical lymph nodes',
  'cervical spine',
  'cervical vertebra',
  'cervical/thoracic/lumbar spine',
  'cervix',
  'chest',
  'chest wall',
  'chest/abdomen/pelvis',
  'chest/pelvis',
  'chin',
  'clavicle',
  'clitoris',
  'coccyx',
  'colon',
  'colon and rectum',
  'colon, mucosa only',
  'common duct',
  'common pelvic',
  'conjunctiva',
  'connective tissue',
  'cranial nerve',
  'descending colon',
  'diaphragm',
  'distant lymph node',
  'distant metastasis',
  'duodenum',
  'ear',
  'ear canal',
  'ear, pinna (external)',
  'effusion',
  'elbow',
  'endocrine gland',
  'epididymis',
  'epidural',
  'epitrochlear lymph nodes',
  'epitrochlear/brachial',
  'esophagus',
  'esophagus, mucosa only',
  'ethmoid bone',
  'external/internal iliac',
  'extra-adrenal site',
  'extremities',
  'eye',
  'fallopian tube',
  'femoral',
  'femoral lymph nodes',
  'femur',
  'fibula',
  'fibula head',
  'finger',
  'floor of mouth',
  'fluid',
  'foot',
  'forearm',
  'forehead',
  'foreskin',
  'frontal bone',
  'frontal lobe',
  'fundus/body',
  'gallbladder',
  'ganglia',
  'gastroesophageal junction',
  'gastrointestinal / abdominal',
  'genitourinary',
  'groin',
  'gum',
  'hand',
  'hard palate',
  'head & neck',
  'head - face or neck, nos',
  'head of pancreas',
  'head/neck/chest/abd/pelvis',
  'heart',
  'hepatic duct',
  'hepatic flexure',
  'hilar',
  'hilar lymph nodes',
  'hilum',
  'hip',
  'humerus',
  'hypopharynx',
  'ileum',
  'iliac',
  'iliac-common',
  'iliac-external',
  'ilium',
  'infraclavicular',
  'infraclavicular/axillary/pectoral',
  'inguinal',
  'inguinal/femoral',
  'inguinal/femoral/iliac',
  'intestine',
  'intraocular',
  'ischium',
  'jaw',
  'jejunum',
  'joints',
  'kidney',
  'knee',
  'lacrimal bone',
  'lacrimal gland',
  'large bowel',
  'large intestine',
  'laryngopharynx',
  'larynx',
  'leg',
  'leptomeninges',
  'ligament',
  'lip',
  'liver',
  'liver and intrahepatic duct',
  'liver/spleen',
  'lower para-aortic',
  'lumbar spine',
  'lumbar vertebra',
  'lung',
  'lymph node(s)',
  'lymph node(s) axilla',
  'lymph node(s) cervical',
  'lymph node(s) distant',
  'lymph node(s) epitrochlear',
  'lymph node(s) femoral',
  'lymph node(s) hilar',
  'lymph node(s) iliac',
  'lymph node(s) iliac-common',
  'lymph node(s) iliac-external',
  'lymph node(s) inguinal',
  'lymph node(s) int mammary',
  'lymph node(s) mammary',
  'lymph node(s) mediastinal',
  'lymph node(s) mesenteric',
  'lymph node(s) occipital',
  'lymph node(s) para aortic',
  'lymph node(s) paracaval',
  'lymph node(s) parotid',
  'lymph node(s) pelvic',
  'lymph node(s) periportal',
  'lymph node(s) popliteal',
  'lymph node(s) regional',
  'lymph node(s) retroperitoneal',
  'lymph node(s) scalene',
  'lymph node(s) splenic',
  'lymph node(s) subclavicular',
  'lymph node(s) submandibular',
  'lymph node(s) supraclav',
  'lymphoma',
  'mammary gland',
  'mandible',
  'maxilla',
  'mediastinal',
  'mediastinal / intra-thoracic',
  'mediastinal lymph nodes',
  'mediastinal soft tissue',
  'mediastinum',
  'mesenteric',
  'mesenteric lymph nodes',
  'mesentery',
  'mesothelium',
  'metacarpus',
  'metatarsus',
  'mini mantle',
  'mouth',
  'muscle',
  'nails',
  'nasal bone',
  'nasal cavity',
  'nasal soft tissue',
  'nasopharynx',
  'neck',
  'neck/chest',
  'neck/chest/abdomen/pelvis',
  'nerve',
  'nerve(s) cranial',
  'no known extranodal involvement',
  'no known nodal involvement',
  'not applicable',
  'occipital',
  'occipital bone',
  'occipital lymph nodes',
  'ocular orbits',
  'omentum',
  'oral cavity',
  'oral cavity, mucosa only',
  'oral tongue',
  'orbit',
  'orbital',
  'oropharyngeal soft tissue',
  'oropharynx',
  'other extranodal site',
  'other nodal',
  'other, specify',
  'ovary',
  'pa/lat',
  'palate',
  'pancreas',
  'para-aortic',
  'paraaortic lymph nodes',
  'paraspinal ganglion',
  'parathyroid',
  'paratracheal',
  'parietal bone',
  'parotid',
  'parotid gland',
  'patella',
  'pectoral',
  'pelvis',
  'penis',
  'peri-orbital soft tissue',
  'perianus',
  'pericardium',
  'peripheral blood',
  'peritoneal cavity',
  'peritoneum',
  'pharynx',
  'pineal gland',
  'pituitary gland',
  'placenta',
  'pleura',
  'pleura/pleural effusion',
  'popliteal',
  'popliteal fossa',
  'popliteal lymph nodes',
  'porta caval',
  'porta hepatis',
  'pre-auricular',
  'primary tumor',
  'prostate',
  'pubis',
  'pulmonary system',
  'pylorus',
  'radius',
  'rectosigmoid junction',
  'rectum',
  'regional cutaneous or subcutaneous tissue (includes satellite & in-transit metastasis)',
  'regional lymph node',
  'retina',
  'retro-orbital area',
  'retroperitoneal',
  'retroperitoneal lymph nodes',
  'ribs',
  'round ligament',
  'sacrum',
  'salivary gland',
  'scalp',
  'scapula',
  'scrotum',
  'seminal vesicle',
  'shoulder',
  'sigmoid colon',
  'sinus',
  'sinus(es), maxillary',
  'skeletal muscle',
  'skin',
  'skull',
  'small bowel, mucosa only',
  'small intestine',
  'soft tissue (muscle, ligaments, subcutaneous)',
  'sphenoid bone',
  'spinal cord',
  'spine',
  'spine/femur',
  'spine/femur/radius',
  'spleen',
  'splenic',
  'splenic flexure',
  'splenic hilar',
  'splenic lymph nodes',
  'sternum',
  'stomach',
  'stomach, mucosa only',
  'subcutaneous tissue',
  'submandibular',
  'submandibular lymph nodes',
  'supraclavicular',
  'supraclavicular lymph nodes',
  'synovium',
  'systemic',
  'tail of pancreas',
  'tarsus',
  'temporal bone',
  'tendon',
  'testes',
  'testicle',
  'thigh',
  'thoracic',
  'thoracic spine',
  'thoracic vertebra',
  'thoracic/lumbar spine',
  'thorax',
  'throat',
  'thymus',
  'thyroid',
  'thyroid gland',
  'tibia',
  'toe',
  'tongue',
  'tongue, base of tongue',
  'tonsil',
  'tonsil, pharyngeal',
  'trachea',
  'trachea/major bronchi',
  'transverse colon',
  'trunk',
  'trunk, superficial',
  'ulna',
  'umbilical cord',
  'unknown',
  'upper extremity',
  'upper para-aortic',
  'ureter',
  'urethra',
  'urinary tract',
  'uterus',
  'uvula',
  'vagina',
  'vas deferens',
  'vein',
  'vena cava, inferior/superior',
  'vertebra',
  'vertebral column',
  'vulva',
  "waldeyer's ring",
  'whole body',
  'wrist',
  'zygomatic bone',
];

export const toExcelHeaders = {
  'breast cancer': 'breast_data_entry_options',
  cholangiocarcinoma: '?',
  'colorectal cancer': 'colon/rectum_data_entry_options',
  'diffuse midline glioma': 'diffuse_midline_glioma_(dipg)_data_entry_options',
  'embryonal tumor': 'embryonal_tumor_data_entry_options',
  'esophageal cancer': 'esophageal_data_entry_options-_final',
  "ewing's sarcoma": 'ewing_sarcoma_data_entry_options-_final',
  glioblastoma: 'glioblastoma_data_entry_options',
  'head and neck cancer': '?',
  hepatoblastoma: 'pediatric_liver_cancer_data_entry_options',
  'hepatocellular carcinoma': 'liver_data_entry_options',
  'liver cancer': '?',
  'low grade glioma': '?',
  'lung cancer': 'lung_adenocarcinoma_data_entry_options',
  medulloblastoma: 'medulloblastoma_data_entry_options',
  melanoma: '?',
  neuroblastoma: 'neuroblastoma_data_entry_options-_final',
  osteosarcoma: 'osteosarcoma_data_entry_options-_final',
  'ovarian cancer': '?',
  'pancreatic cancer': 'pancreas_data_entry_options-_final',
  'prostate cancer': '?',
  rhabdomyosarcoma: 'rhabdomyosarcoma_data_entry_options-_final',
  'stomach cancer': 'stomach_data_entry_options',
  'thyroid cancer': '?',
  'wilms tumor': 'wilms_tumor_data_entry_options',
};

export const toExcelRowNumber = {
  'histological type': 0,
  'clinical stage grouping': 12,
  'site of sample acquisition': 3,
  'tumor histological grade': 22,
};

export const clinicalTumorDiagnosis = [
  'breast cancer',
  'cholangiocarcinoma',
  'colorectal cancer',
  'diffuse midline glioma',
  'embryonal tumor',
  'esophageal cancer',
  "ewing's sarcoma",
  'glioblastoma',
  'head and neck cancer',
  'hepatoblastoma',
  'hepatocellular carcinoma',
  'liver cancer',
  'low grade glioma',
  'lung cancer',
  'medulloblastoma',
  'melanoma',
  'neuroblastoma',
  'osteosarcoma',
  'ovarian cancer',
  'pancreatic cancer',
  'prostate cancer',
  'rhabdomyosarcoma',
  'stomach cancer',
  'thyroid cancer',
  'wilms tumor',
];

// this is generated from /wrangle-cde/sheet-id/tab-name endpoint
export const clinicalTumorDiagnosisDependent = {
  'histological type': {
    'breast cancer': [
      'Infiltrating ductal carcinoma',
      'Infiltrating lobular carcinoma',
      'Mucinous carcinoma',
      'Medullary carcinoma',
      'Metaplastic ductal carcinoma',
      'Infiltrating carcinoma (NOS)',
      'Mixed histology (specify)',
      'Other (specify, CDE ID: 3124492)',
      'Unknown',
    ],
    cholangiocarcinoma: [],
    'colorectal cancer': [
      'Adenocarcinoma',
      'Mucinous adenocarcinoma',
      'Signet ring cell carcinoma',
      'Medullary carcinoma',
      'Micropapillary carcinoma',
      'Serrated adenocarcinoma',
      'Large cell neuroendocrine carcinoma',
      'Small cell neuroendocrine carcinoma',
      'Neuroendocrine carcinoma (poorly differentiated)',
      'Squamous cell carcinoma',
      'Adenosquamous carcinoma',
      'Undifferentiated carcinoma',
      'Carcinoma, type cannot be determined',
      'Other (specify)',
    ],
    'diffuse midline glioma': ['N/A'],
    'embryonal tumor': [
      'ETMR',
      'Medulloepithelioma',
      'CNS neuroblastoma',
      'CNS ganglioneuroblastoma',
      'CNS atypical teratoid/rhabdoid tumor',
      'NOS',
    ],
    'esophageal cancer': [
      'Esophagus adenocarcinoma (NOS), Esophagus squamous cell carcinoma, Unknown',
      'Other histology (please specify, CDE ID: 3124492)',
    ],
    "ewing's sarcoma": [],
    glioblastoma: ['Giant cell glioblastoma', 'Gliosarcoma', 'NOS'],
    'head and neck cancer': [],
    hepatoblastoma: [],
    'hepatocellular carcinoma': [
      'Hepatocellular carcinoma',
      'Fibrolamellar hepatocellular carcinoma',
      'Hepatocholangiocarcinoma (mixed)',
      'Unknown',
    ],
    'liver cancer': [],
    'low grade glioma': [],
    'lung cancer': [
      'Acinar Adenocarcinoma',
      'Lepidic adenocarcinoma',
      'Papillary Adenocarcinoma',
      'Solid adenocarcinoma',
      'Minimally invasive adenocarcinoma, mucinous',
      'Minimally invasive adenocarcinoma, nonmucinous',
      'Micropapillary Adenocarcinoma',
      'Fetal Adenocarcinoma',
      'Enteric adenocarcinoma',
      'Colloid adenocarcinoma',
      'Fetal adenocarcinoma',
      'Mucinous (Colloid) Adenocarcinoma',
      'Signet Ring Adenocarcinoma',
      'Adenocarcinoma in situ, mucinous',
      'Adenocarcinoma in situ, nonmucinous',
      'Adenocarcinoma (NOS)',
      'Unknown',
    ],
    medulloblastoma: [
      'Classic medulloblastoma',
      'Indeterminate medulloblastoma',
      'Large cell/anaplastic medulloblastoma',
      'Desmoplastic/nodular medulloblatoma ',
      'Medulloblastoma with extensive nodularity',
      'NOS',
    ],
    melanoma: [],
    neuroblastoma: ['Favorable', 'Unfavorable', 'Unknown'],
    osteosarcoma: ['Osteoblastic', 'Chondroblastic', 'Fibroblastic', 'Telangiectatic'],
    'ovarian cancer': [],
    'pancreatic cancer': [
      'Adenocarcinoma ductal type ',
      'Signet ring cell carcinoma',
      'Intraductal papillary mucinous neoplasm (IPMN, main duct/mixed) ',
      'Intraductal papillary mucinous neoplasm (IPMN, Side duct) ',
      'Invasive adenocarcinoma arising from IPMN ',
      'Mucinous cystic neoplasms (MCN) ',
      'Invasive carcinoma arising in MCN',
      'Serous cystic adenoma (SCA)',
      'Serous cystadenocarcinoma ',
      'Acinar cell carcinoma ',
      'Acinar cell cystadenocarcinoma',
      'Mixed acinar-ductal carcinomas',
      'Mixed ductal-neuroendocrine carcinoma',
      'Mixed acinar-neuroendocrine carcinoma',
      'High-grade neuroendocrine carcinoma (large cell type)',
      'High-grade neuroendocrine carcinoma (small cell type)',
      'Hepatoid carcinoma',
      'Solid pseudopapillary neoplasm ',
      'Inflammatory myofibroblastic tumor ',
      'Pancreatoblastoma ',
      'Pancreas colloid (mucinous non-cystic) carcinoma ',
      'Medullary carcinoma ',
      'Undifferentiated (anaplastic) carcinoma ',
      'Undifferentiated carcinoma with osteoclast-like giant cells ',
      'Adenocarcinoma (other subtype, specify, CDE ID: 3124492) ',
      'Unknown ',
    ],
    'prostate cancer': [],
    rhabdomyosarcoma: ['Alveolar', 'Embryonal', 'Other'],
    'stomach cancer': [
      'Stomach intestinal adenocarcinoma-tubular type',
      'Stomach intestinal adenocarcinoma-papillary type',
      'Stomach intestinal adenocarcinoma-mucinous type',
      'Stomach intestinal carcinoma-type NOS',
      'Stomach adenocarcinoma-signet ring type',
      'Stomach adenocarcinoma-diffuse type',
      'Stomach adenocarcinoma-NOS',
      'Unknown',
    ],
    'thyroid cancer': [],
    'wilms tumor': [],
  },
  'clinical stage grouping': {
    'breast cancer': [
      'Stage X',
      'Stage Tis',
      'Stage 0',
      'Stage I',
      'Stage IA',
      'Stage IB',
      'Stage II',
      'Stage IIA',
      'Stage IIB',
      'Stage III',
      'Stage IIIA',
      'Stage IIIB',
      'Stage IIIC',
      'Stage IV',
    ],
    cholangiocarcinoma: [],
    'colorectal cancer': [
      'Stage I',
      'Stage IA',
      'Stage IB',
      'Stage II',
      'Stage IIA',
      'Stage IIB',
      'Stage IIC',
      'Stage III',
      'Stage IIIA',
      'Stage IIIB',
      'Stage IIIC',
      'Stage IV',
      'Stage IVA',
      'Stage IVB',
    ],
    'diffuse midline glioma': [],
    'embryonal tumor': [],
    'esophageal cancer': [
      'Stage 0',
      'Stage I',
      'Stage IA',
      'Stage IB',
      'Stage II',
      'Stage IIA',
      'Stage IIB',
      'Stage III',
      'Stage IIIA',
      'Stage IIIB',
      'Stage IIIC',
      'Stage IV',
      'Stage IVA',
      'Stage IVB',
    ],
    "ewing's sarcoma": ['Localized', 'Regional spread', 'Distant', 'Unknown'],
    glioblastoma: [],
    'head and neck cancer': [],
    hepatoblastoma: [],
    'hepatocellular carcinoma': [
      'Stage I',
      'Stage IA',
      'Stage IB',
      'Stage II',
      'Stage IIA',
      'Stage IIB',
      'Stage III',
      'Stage IIIA',
      'Stage IIIB',
      'Stage IIIC',
      'Stage IV',
      'Stage IVA',
      'Stage IVB',
    ],
    'liver cancer': [],
    'low grade glioma': [],
    'lung cancer': [
      'Stage 0',
      'Stage IA1',
      'Stage IA2',
      'IA3',
      'Stage IB',
      'Stage II',
      'Stage IIA',
      'Stage IIB',
      'Stage III',
      'Stage IIIA',
      'Stage IIIB',
      'Stage IV',
    ],
    medulloblastoma: [],
    melanoma: [],
    neuroblastoma: ['INRGSS:', 'L1', 'L2', 'M', 'MS'],
    osteosarcoma: [
      'COG Osteosarcoma Stage:',
      'Localized',
      'Certain metastatic',
      'Possible metastatic',
      'Unknown',
    ],
    'ovarian cancer': [],
    'pancreatic cancer': [
      'Stage I',
      'Stage IA',
      'Stage IB',
      'Stage IIA',
      'Stage IIB',
      'Stage III',
      'Stage IV',
    ],
    'prostate cancer': [],
    rhabdomyosarcoma: ['TNM Stage:', '1', '2', '3', '4'],
    'stomach cancer': [
      'Stage I',
      'Stage IA',
      'Stage IB',
      'Stage II',
      'Stage IIA',
      'Stage IIB',
      'Stage III',
      'Stage IIIA',
      'Stage IIIB',
      'Stage IIIC',
      'Stage IV',
    ],
    'thyroid cancer': [],
    'wilms tumor': [],
  },
  'site of sample acquisition': {
    'breast cancer': ['Right breast', 'Left breast', 'Other (specify, CDE ID: 5946219)'],
    cholangiocarcinoma: [],
    'colorectal cancer': [
      'Cecum',
      'Ileocecal valve',
      'Sigmoid colon',
      'Splenic flexure',
      'Ascending colon',
      'Ascending colon hepatic flexure',
      'Descending colon',
      'Transverse colon',
      'Rectum',
      'Rectosigmoid junction',
      'Other',
    ],
    'diffuse midline glioma': ['Brain', 'Other (specify, CDE ID: 5946219)', 'Unknown'],
    'embryonal tumor': ['Brain', 'Other (specify, CDE ID: 5946219)', 'Unknown'],
    'esophageal cancer': [
      'Esophagus - proximal third',
      'Esophagus - middle third',
      'Esophagus - distal third',
      'Gastroesophageal junction',
      'Other (specify, CDE ID: 5946219)',
    ],
    "ewing's sarcoma": [
      'Upper extremity',
      'Lower extremity',
      'Pelvis',
      'Spine',
      'Soft tissue',
      'Other (specify, CDE ID: 5946219)',
    ],
    glioblastoma: ['Brain', 'Other (specify, CDE ID: 5946219)', 'Unknown'],
    'head and neck cancer': [],
    hepatoblastoma: [],
    'hepatocellular carcinoma': ['Liver', 'Other (specify, CDE ID: 5946219)'],
    'liver cancer': [],
    'low grade glioma': [],
    'lung cancer': [
      'Right upper lobe lung',
      'Right middle lobe lung',
      'Right lower lobe lung',
      'Left upper lobe lung',
      'Left lower lobe lung',
      'Bronchus',
      'Other (specify, CDE ID: 5946219)',
    ],
    medulloblastoma: ['Brain', 'Other (specify, CDE ID: 5946219)', 'Unknown'],
    melanoma: [],
    neuroblastoma: [
      'Adrenal',
      'Posterior mediastinum',
      'Abdominal/non-adrenal',
      'Neck',
      'Other Other (specify, CDE ID: 5946219)',
    ],
    osteosarcoma: [
      'Upper extremity',
      'Lower extremity',
      'Pelvis',
      'Spine',
      'Lung',
      'Other (specify, CDE ID: 5946219)',
    ],
    'ovarian cancer': [],
    'pancreatic cancer': [
      'Pancreatic head',
      'Pancreatic body',
      'Pancreatic tail',
      'Liver',
      'Peritoneum',
      'Lymph nodes',
      'Other (specify, CDE ID: 5946219)',
    ],
    'prostate cancer': [],
    rhabdomyosarcoma: [
      'Orbit',
      'Head and neck (non-PM)',
      'Genitourinary NOS',
      'Biliary tract/liver',
      'Bladder',
      'Prostate',
      'Extremity',
      'Parameningeal',
      'Other (specify, CDE ID: 5946219)',
    ],
    'stomach cancer': [
      'Gastroesophageal junction',
      'Cardia/proximal',
      'Fundus/body',
      'Antrum/distal',
      'Stomach (NOS)',
      'Other (specify, CDE ID: 5946219)',
    ],
    'thyroid cancer': [],
    'wilms tumor': [],
  },
  'tumor histological grade': {
    'breast cancer': [
      'Histopathologic Grade',
      'Well differentiated',
      'Moderately differentiated',
      'Poorly differentiated',
      'Unknown',
    ],
    cholangiocarcinoma: [],
    'colorectal cancer': [
      'GX-Unknown',
      'G1-Well differentiated',
      'G2-Moderately differentiated',
      'G3-Poorly differentiated',
      'G4-Undifferentiated',
      'GB-Borderline histologic grade',
    ],
    'diffuse midline glioma': ['Grade 4'],
    'embryonal tumor': ['Grade 4'],
    'esophageal cancer': [],
    "ewing's sarcoma": [],
    glioblastoma: ['Grade 4'],
    'head and neck cancer': [],
    hepatoblastoma: [],
    'hepatocellular carcinoma': [],
    'liver cancer': [],
    'low grade glioma': [],
    'lung cancer': [
      'GX-Unknown',
      'G1-Well differentiated',
      'G2-Moderately differentiated',
      'G3-Poorly differentiated',
      'G4-Undifferentiated',
      'GB-Borderline histologic grade',
    ],
    medulloblastoma: ['Grade 4'],
    melanoma: [],
    neuroblastoma: [],
    osteosarcoma: [],
    'ovarian cancer': [],
    'pancreatic cancer': ['WHO Grade', 'Grade 1', 'Grade 2', 'Grade 3'],
    'prostate cancer': [],
    rhabdomyosarcoma: [],
    'stomach cancer': [],
    'thyroid cancer': [],
    'wilms tumor': [],
  },
};

// One of options for Yup and front-end components

export const modelType = [
  '3-d: organoid',
  '3-d: other (neurosphere)',
  '2-d: conditionally reprogrammed cells',
  '2-d: adherent',
  '2-d: suspension',
];

export const molecularCharacterizations = [
  'whole genome sequencing (wgs) of "parent" tumor',
  'wgs of normal',
  'wgs of model',
  'whole exome sequencing (wxs) of parent tumor',
  'wxs of normal',
  'wxs of model',
  'targeted sequencing of parent tumor',
  'targeted sequencing of normal',
  'targeted sequencing of model',
  'rna-seq of parent tumor',
  'rna-seq of model',
];

export const splitRatio = ['1:2', '1:4', '1:8'];

export const gender = ['female', 'male', 'unspecified', 'unknown'];

export const race = [
  'american indian or alaskan native',
  'asian',
  'black or african american',
  'native hawaiian or other pacific islander',
  'white',
  'not reported',
  'unknown',
];

export const neoadjuvantTherapy = [
  'no',
  'yes, pharmaceutical treatment',
  'yes, radiation',
  'yes, both radiation and pharmaceutical treatment',
];

export const diseaseStatus = [
  'disease free',
  'progression (no response to treatment)',
  'relapse (patient responded to treatment)',
  'unknown / lost to followup',
];

export const vitalStatus = ['alive', 'dead', 'unknown/lost to followup'];

export const therapy = [
  'targeted therapy (small molecule inhibitors and targeted antibodies)',
  'immunotherapy (cellular and immune checkpoint)',
  'hormonal therapy',
  'radiation therapy',
  'other',
  'none',
];

export const variantTypes = ['Clinical', 'Histopathological Biomarker'];

export const variantAssessmentType = [
  'IHC',
  'CISH',
  'FISH',
  'Pyrosequencing/methylation-specific PCR',
];

export const variantExpressionLevel = ['Positive', 'Negative', 'Equivocal'];
